Repository rexdivakar/Notifly, pull requests merged in 2020-10, with the labels that each got.

#12 Feature/parameter updates
  telegram/notifly.py
Labels: quick-fix

#18 File Download
  telegram/notifly.py
Labels: enhancement, hacktoberfest-accepted

#19 Resolve image issue in website
  README.md
Labels: bug, documentation
